name: Hello world
on: workflow_dispatch
jobs: 
      print-hello-world-linux:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"
              name: Print Hello World
        
      print-hello-world-windows:
        runs-on:  windows-latest
        steps:
            - name: Print Hello
              run: echo "Hello"
              
          
